import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative  bg-gray-50 pt-28 text-gray-950 sm:pt-36`}
      >
        <div
          className="absolute right-[11rem] top-[-6rem] -z-10 h-[32.25rem] w-[31.25rem] 
        rounded-full bg-[#fbe2e3] blur-[10rem] sm:w-[68.7rem]"
        ></div>
        <div
          className="absolute left-[-35rem] top-[-1rem] -z-10 h-[32.25rem] w-[50rem] 
        rounded-full bg-[#dbd7fb] blur-[10rem] sm:w-[68.7rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"
        ></div>
        <Header />
        {children}
      </body>
    </html>
  );
}
